
msg_0:
[color(yellow)]Officer from Main Branch[color(white)]
[tab]So, Anna Yoshizaka-san started to behave like a
[tab]delinquent after the hit-and-run by Kaneda?
[sync][wait][clear][end]

msg_1:
[color(yellow)]Ms. Saeko[color(white)]
[tab]I didn’t say that! Stop putting words in my mouth! 
[tab]Anna is not the kind of person who could 
[tab]kill someone!
[sync][wait][clear][end]

msg_2:
[color(yellow)]Young Detective[color(white)]
[tab]Miss, please calm down.
[tab]We do not suspect that that student is
[tab]capable of these crimes.
[sync][wait][clear][end]

msg_3:
[color(yellow)]Young Detective[color(white)]
[tab]No normal person could have done something
[tab]like that...
[sync][wait][clear][end]

msg_4:
[color(yellow)]Officer from Main Branch[color(white)]
[tab]Sergeant [suou], please... I can do without
[tab]the commentary on the situation...
[sync][wait][clear][end]

msg_5:
[color(yellow)]Officer from Main Branch[color(white)]
[tab]I guess that will do for now...
[tab]Thank you for your cooperation,
[tab]Ms. Saeko.
[sync][wait][clear][end]

msg_6:
[color(yellow)]Ms. Saeko[color(white)]
[tab]You’re [tatsuya] [suou]’s brother, right?
[tab]Has he come back home?
[sync][wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]...No, he hasn’t.
[tab]What the hell does he think he’s doing?
[sync][wait][clear][end]

msg_8:
[color(yellow)]Katsuya [suou][color(white)]
[tab][color(green)]Young Detective of the Kounan PD.
[tab]His current rank is Sergeant.
[tab]He has a little brother named [tatsuya]. [color(white)]
[sync][wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]I’m sorry that he’s worrying you, too.
[tab]Please excuse me, but I must be going.
[sync][wait][clear][end]

msg_10:
[color(yellow)]Ulala[color(white)]
[tab]Were those guys from the Police Department?
[sync][wait][clear][end]

msg_11:
[color(yellow)]Ms. Saeko[color(white)]
[tab]Yes...
[sync][wait][clear][end]

msg_12:
[color(yellow)]Ms. Saeko[color(white)]
[tab]You work for Kismet, right? Mayuzumi told
[tab]me that you were coming down to interview
[tab]some of our students.
[sync][wait][clear][end]

msg_13:
[color(yellow)]Saeko Takami[color(white)]
[tab][color(green)]Teacher of class 3-B.
[tab]She is very liberal-minded, and she
[tab]was hired for her policy on freedom.[color(white)]
[sync][wait][clear][end]

msg_14:
[color(yellow)]Ulala[color(white)]
[tab]It won’t take long, but...
[tab]Are you sure it’s alright?
[sync][wait][clear][end]

msg_15:
[color(yellow)]Ms. Saeko[color(white)]
[tab]I think it’s fine, but...
[tab]Please be careful... Some of the students
[tab]are still a little shaken after the murders...
[sync][wait][clear][end]

msg_16:
[color(yellow)]Ulala[color(white)]
[tab]You mean... something happened?
[sync][wait][clear][end]

msg_17:
[color(yellow)]Ms. Saeko[color(white)]
[tab]The man who ran over a student died, 
[tab]and it’s somehow related to the bizarre murders...
[tab]I hope they’re wrong...
[sync][wait][clear][end]

msg_18:
[color(yellow)]Ms. Saeko[color(white)]
[tab]The rumors about the Joker?
[tab]The Joker is the only thing that the
[tab]students talk about anymore.
[sync][wait][clear][end]

msg_19:
[color(yellow)]Ms. Saeko[color(white)]
[tab]Supposedly, the Joker is the one who kills
[tab]a person you don’t like by calling your
[tab]own cell phone.
[wait][clear][end]

msg_20:
[color(yellow)]Ms. Saeko[color(white)]
[tab]I don’t know who started it, but it’s creepy.
[tab]It was a lot cuter when they were just
[tab]playing "fortune teller"...
[sync][wait][clear][end]

msg_21:
[color(yellow)]Ms. Saeko[color(white)]
[tab]Anyway, I told them to stay in their classrooms.
[tab]I hope some backup arrives soon...
[wait][clear][end]

msg_22:
[color(yellow)]Ulala[color(white)]
[tab]Speaking of which, you said that 
[tab]D五j二 Vu Boy goes here, didn’t you...?
[tab]Maybe you could meet up with him?
[wait][clear][end]

msg_23:
[color(yellow)]Ulala[color(white)]
[tab]I thought that the Joker was just a rumor...
[tab]That’s... why... I...
[tab]I never thought a rumor would become real.
[wait][clear][end]

msg_24:
[color(yellow)]Mr. Kashihara[color(white)]
[tab]Hello.
[tab]I’m a fan of Kismet’s occult magazine.
[tab]You know, the monthly, "May"?
[wait][clear][end]

msg_25:
[color(yellow)]Akinari Kashihara[color(white)]
[tab][color(green)]World History teacher for seniors.
[tab]Though strange, he is a kind teacher.[color(white)]
[wait][clear][end]

msg_26:
[color(yellow)]Mr. Kashihara[color(white)]
[tab]I used to write books like 
[tab]"UFO discovered Underneath City!" but now, 
[tab]I like to enjoy them as entertainment.
[wait][clear][end]

msg_27:
[color(yellow)]Mr. Kashihara[color(white)]
[tab]I can’t believe the principal was killed.
[tab]Co, Could it be, the Last Battalion...?
[tab]N-No, that can’t be...
[wait][clear][end]

msg_28:
[color(yellow)]Akinari Kashihara[color(white)]
[tab][color(green)]World History teacher for seniors.
[tab]Though strange, he is a kind teacher.[color(white)]
[wait][clear][end]

msg_29:
[color(yellow)]Mr. Kashihara[color(white)]
[tab]Hello.
[tab]I’m a fan of Kismet’s occult magazine.
[tab]You know, the monthly, "May"?
[wait][clear][end]

msg_30:
[color(yellow)]Mr. Kashihara[color(white)]
[tab]I used to write books like 
[tab]"UFO discovered Underneath City!" but now, 
[tab]I like to enjoy them as entertainment.
[wait][clear][end]

msg_31:
[color(yellow)]Mr. Kashihara[color(white)]
[tab]I can’t believe the principal was killed.
[tab]Co, Could it be, the Last Battalion...?
[tab]N-No, that can’t be...
[wait][clear][end]

msg_32:
[color(yellow)]Mr. Oriri[color(white)]
[tab]Really, interviewing our students?
[tab]But last period is over already,
[tab]so there aren’t that many students left.
[wait][clear][end]

msg_33:
[color(yellow)]Mr. Oriri[color(white)]
[tab]Oh really, the Principal killed? ...Really.
[tab]...So the suspect might still be in
[tab]the school? Really.
[wait][clear][end]

msg_34:
[color(yellow)]Mr. Aishi[color(white)]
[tab]I see, another murder, I see!
[tab]And the one killed is the guy who hit Anna!
[tab]I see! That’s why the police are here!
[wait][clear][end]

msg_35:
[color(yellow)]Mr. Aishi[color(white)]
[tab]I see!
[tab]A murder in the principal’s office!
[tab]I see! This is serious!
[wait][clear][end]

msg_36:
[color(yellow)]Mr. Aishi[color(white)]
[tab]...So help me out!
[tab]I see! So, you WILL help me!?
[tab]Thank you!
[wait][clear][color(yellow)]Mr. Aishi[color(white)]
[tab]I have to check all the rooms! So go
[tab]check the clock tower on the fourth floor!
[tab]Here’s the [color(green)][var(msg_var_0)][color(white)]! Good luck!!
[wait][clear][end]

msg_37:
[color(yellow)]Mr. Aishi[color(white)]
[tab]So what’s wrong?
[tab]Huh--? The clock tower key is missing
[tab]from the faculty room?
[wait][clear][color(yellow)]Mr. Aishi[color(white)]
[tab]Mu---!? I wonder who took it out?
[tab]Here’s a spare [color(green)][var(msg_var_0)][color(white)]!
[tab]Please use it--!!
[wait][clear][end]

msg_38:
[color(green)]Maya got [item_with_type(item_ffff)].[color(white)]
[wait][clear][end]

msg_39:
[color(yellow)]Mr. Aishi[color(white)]
[tab]The suspect could still be around-!!
[tab]That’s scary-!
[tab]Are the students safe-!?
[wait][clear][end]

msg_40:
[color(yellow)]Katsuya[color(white)]
[tab]Helios... So that’s another "me", they say...
[tab]Another me, oblivious to myself...
[tab]How ironic that it has to be a cat.
[wait][clear][end]
