
msg_0:
[color(yellow)]Yukino[color(white)]
[tab]Good job on the coverage.
[tab]There’s a letter for you, Maya-san.
[tab]But there’s no return address on it...
[sync][wait][clear][end]

msg_1:
[tab]But there’s no return address on it...
[choice(2)]Thanks, Yukki----!
Thanks. But, who could it be from?
[end_choice][clear][end]

msg_2:
[color(yellow)]Maya Amano[color(white)]
[tab][color(green)]Editor of Kismet Publishing’s teen magazine, Coolest.
[tab]The game’s main character.
[color(white)][sync][wait][clear][end]

msg_3:
[color(yellow)]Maya Amano[color(white)]
[tab][color(green)]Editor of Kismet Publishing’s teen magazine, Coolest.
[tab]The game’s main character.
[color(white)][sync][wait][clear][end]

msg_4:
[color(yellow)]Letter[color(white)]
[tab]yOu’rE nEXt...
[tab]                   JOKER
[sync][wait][clear][end]

msg_5:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . . . . ?
[sync][wait][clear][end]

msg_6:
[color(yellow)]Rookie Reporter[color(white)]
[tab]Amano-senpai, the Chief wants to see you.
[sync][wait][clear][end]

msg_7:
[color(yellow)]Rookie Reporter[color(white)]
[tab]It must be rough, always getting the difficult jobs...
[sync][wait][clear][end]

msg_8:
[color(yellow)]Rookie Reporter[color(white)]
[tab]Even if I work hard, it does no good.
[tab]Dreams and reality are such...
[tab](sigh) Maybe I should just quit...
[sync][wait][clear][end]
