
msg_0:
[color(yellow)]Old Woman[color(white)]
[tab]You look so depressed...
[tab]Did you lose something important?
[sync][wait][clear][end]

msg_1:
[color(yellow)]Young Man[color(white)]
[tab]. . . . . . . . . .
[sync][wait][clear][end]

msg_2:
[color(yellow)]Old Woman[color(white)]
[tab]I see... You didn’t lose anything.
[tab]You found... your memories.
[sync][wait][clear][end]

msg_3:
[color(yellow)]Old Woman[color(white)]
[tab]Humans are such sinful creatures.
[tab]This place was so lively with activity...
[tab]As time passes, things dear are forgotten.
[sync][wait][clear][end]

msg_4:
[color(yellow)]Old Woman[color(white)]
[tab]Would you be better off forgetting them,
[tab]or remembering them...? 
[tab]You’ve been enslaved by this dilemma...
[sync][wait][clear][end]

msg_5:
[color(yellow)]Young Man[color(white)]
[tab]That’s right... I remember now...
[tab]A sin that must not exist...
[tab]How do I atone...?
[sync][wait][clear][end]
