
msg_0:
[color(yellow)]Receptionist[color(white)]
[tab]Ah, Maya.
[tab]Your friend hasn’t come yet.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Ciao, Ma-ya!
[tab]Hey, if we don’t hurry, all the good men will be taken!
[sync][wait][clear][end]

msg_2:
[color(yellow)]Ulala Serizawa[color(green)]
[tab]Maya’s friend who sells lingerie. A girl skilled
[tab]with cosmetics and infatuated with fortunes. 
[tab]Her bad luck with men has given her a complex.
[sync][wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]WHAT!?
[tab]What do you mean you have to work!?
[sync][wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]Don’t give me that... You weren’t planning
[tab]on going anyway, huh?
[sync][wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]Oh, I know what it is. You’re still
[tab]thinking about your "D五j二 Vu Boy", huh?
[tab]Ka----! I told you to just forget about him!
[sync][wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Besides, how close can you be to a boy that
[tab]you bumped into once at a train station?
[tab]Even if you felt you’ve met him before...
[sync][wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]What? You’re not kidding about this work thing?
[sync][wait][clear][end]

msg_8:
[color(yellow)]Ulala[color(white)]
[tab]I’ve got an idea! Let me come with you!
[tab]You’ll be able to finish your work in half the
[tab]time, and we might still make it.
[sync][wait][clear][end]

msg_9:
[color(yellow)]Ulala[color(white)]
[tab]See, look! The Wang Long is saying,
[tab]"Today is the day of fateful meetings".
[tab]We’re gonna go to that party!
[sync][wait][clear][end]

msg_10:
[color(yellow)]Receptionist[color(white)]
[tab]What’s wrong Maya?
[tab]You can’t go to the party because of work?
[tab]Mizuno gets off on pushing people around.
[wait][clear][end]

msg_11:
[color(yellow)]Emergency Exit[color(green)]
[tab]You cannot enter here.[color(white)]
[sync][wait][clear][end]
