
msg_0:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]There you are... Amano.
[sync][wait][clear][end]

msg_1:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab][color(green)]Coolest’s Editor-in-Chief who hates Maya.
[tab]An experienced woman who goes by the book.
[tab]30-something and still not married.
[color(white)][sync][wait][clear][end]

msg_2:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]You know why you were called in, right?
[tab]That interview project you turned in...
[tab]"Dream of the Rumored Student"... was crap.
[sync][wait][clear][end]

msg_3:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]It’s boring.
[tab]It has no impact.
[tab]Who would want to read about a green brat?
[sync][wait][clear][end]

msg_4:
[tab]Who would want to read about a green brat?
[choice(2)]Huh...?
I thought it was important.
[end_choice][clear][end]

msg_5:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]That’s a half-hearted answer...
[tab]It doesn’t matter anyway.
[tab]I’m having you cover the Joker rumor.
[sync][wait][clear][end]

msg_6:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]The kids are saying that the recent series
[tab]of murders are the work of the Joker...
[sync][wait][clear][end]

msg_7:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]Get your ass over to Seven Sisters High
[tab]and get the scoop. I’m taking Mayuzumi
[tab]off this job, so you’ll be on your own.
[sync][wait][clear][end]

msg_8:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]Oh, by the way... 
[tab]You can just forget about this afternoon... 
[tab]the time off you asked for...
[sync][wait][clear][end]

msg_9:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]If you don’t like it, I’ve got plenty of
[tab]other reporters that would love to take
[tab]your spot. So, what are you waiting for?
[sync][wait][clear][end]

msg_10:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]Are you arguing with me!? If you like your job, 
[tab]you better get started on the Joker story!
[sync][wait][clear][end]

msg_11:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]You know the rumors the kids are telling
[tab]about how the recent series of bizarre
[tab]murders are the work of the Joker, right?
[sync][wait][clear][end]

msg_12:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]Get your ass over to Seven Sisters High 
[tab]and get the scoop. I’m taking Mayuzumi
[tab]off this job, so you’ll be on your own.
[sync][wait][clear][end]

msg_13:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]Oh, by the way... 
[tab]You can just forget about this afternoon... 
[tab]the time off you asked for...
[sync][wait][clear][end]

msg_14:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]If you don’t like it, I’ve got plenty of
[tab]other reporters that would love to take
[tab]your spot. So, what are you waiting for?
[sync][wait][clear][end]

msg_15:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]Young people these days...
[tab]They can’t work, but they can sure argue.
[sync][wait][clear][end]

msg_16:
[color(yellow)]Coolest’s Sales Chart[color(white)]
[tab][color(green)]Sales numbers are dropping.
[tab]That’s why the Chief is angry.
[tab][color(white)]
[sync][wait][clear][end]

msg_17:
[color(yellow)]Magazine rack[color(white)]
[tab][color(green)]There are back issues of Coolest.
[color(white)]
[sync][wait][clear][end]
