
msg_0:
[color(yellow)]Yukino[color(white)]
[tab]Maya-san, someone named "Serizawa" called 
[tab]for you while you were in that meeting. 
[tab]She said she’d meet you at the reception area.
[sync][wait][clear][end]

msg_1:
[color(yellow)]Yukino Mayuzumi[color(white)]
[tab][color(green)]Maya’s ex-partner and apprentice.
[tab]She’s not really an employee at Kismet, 
[tab]but an assistant photographer hired by Fujii.[color(white)]
[sync][wait][clear][end]

msg_2:
[color(yellow)]Yukino[color(white)]
[tab]Wait, you’re going to a party, huh?
[tab]To hell with the weekends...
[tab]Sometimes you just gotta have a good time.
[sync][wait][clear][end]

msg_3:
[color(yellow)]Yukino[color(white)]
[tab]What!? You have to work this afternoon!?
[tab]Give me 5 minutes.
[tab]I’ll straighten that bitch out!!
[sync][wait][clear][end]

msg_4:
[tab]I’ll complain for you!!
[choice(2)]Thanks, Yukki, but it’s alright...
Let’s think positive! It’s nothing.
[end_choice][clear][end]

msg_5:
[color(yellow)]Yukino[color(white)]
[tab]It’s bad enough that she split us up...
[tab]Now, you can’t take some time off!
[tab]Don’t give into her, Maya-san!
[sync][wait][clear][end]

msg_6:
[color(yellow)]Yukino[color(white)]
[tab]If you’re going over to Sevens, 
[tab]let me call up one of my old teachers.
[tab]She’ll be able to help you out...
[sync][wait][clear][end]

msg_7:
[color(yellow)]Fujii[color(white)]
[tab]Mizuno can be pretty rough... 
[tab]It’s unfortunate that she broke you two up, 
[tab]but she’s the boss... Good luck, Makki.
[sync][wait][clear][end]

msg_8:
[color(yellow)]Shunsuke Fujii[color(white)]
[tab][color(green)]A freelance photographer.
[tab]He’s also Yukino’s highly-respected boss.
[tab]He calls Yukino "Yukki" and Maya "Makki".[color(white)]
[sync][wait][clear][end]

msg_9:
[color(yellow)]Fujii[color(white)]
[tab]Geez... Ms. Mizuno is being pretty rough.
[tab]It’s saddening that you’re not with Yukki,
[tab]but this is business. Good luck, Makki.
[sync][wait][clear][end]

msg_10:
[color(yellow)]Rookie Reporter[color(white)]
[tab]I heard Tasaki-senpai and the Chief talking
[tab]about making you cover the Joker story
[tab]by yourself...
[sync][wait][clear][end]

msg_11:
[color(yellow)]Rookie Reporter[color(white)]
[tab]That way, you’d keep your mouth shut...
[tab]I wonder why I put up with this...
[sync][wait][clear][end]

msg_12:
[color(yellow)]Colleague[color(white)]
[tab]All this fuss about Armageddon and Grand
[tab]Cross, and nothing happened this summer...
[tab]The more hype, the more people complain.
[sync][wait][clear][end]

msg_13:
[color(yellow)]Co-Worker[color(white)]
[tab]Help me sort these "Wang Long" letters.
[tab]Things boomed when the fortunes came true.
[tab]Now, letters requesting fortunes pour in!
[sync][wait][clear][end]

msg_14:
[color(yellow)]Co-Worker[color(white)]
[tab]Do you know that Guardian Dragon stuff
[tab]all the girls are talking about over the net?
[sync][wait][clear][end]

msg_15:
[color(yellow)]Co-Worker[color(white)]
[tab]It’s a Feng Shui style, "Wang Long"
[tab]made easier to understand.
[tab]It gives really accurate readings.
[sync][wait][clear][end]

msg_16:
[color(yellow)]Co-Worker[color(white)]
[tab]Wang Long is a fortune telling style where
[tab]you use the movement of 12 dragons sent
[tab]from the Heavens to predict your future.
[sync][wait][clear][end]

msg_17:
[color(yellow)]Co-Worker[color(white)]
[tab]It’s actually an energy flow like "Chi-Myaku".
[tab]So if you’re good, good things will happen.
[tab]If you’re bad, well you know...
[sync][wait][clear][end]

msg_18:
[color(yellow)]Co-Worker[color(white)]
[tab]There’s no escaping fate, I guess...
[sync][wait][clear][end]

msg_19:
[color(yellow)]Reporter[color(white)]
[tab]Amano, you’re born in July, right?
[tab]So you’re a Dragon of Light, and February’s
[tab]Blue Dragon... Damn, we’re not compatible...
[sync][wait][clear][end]

msg_20:
[color(yellow)]Tasaki[color(white)]
[tab]Amano-san, you’re doing the Joker story, right? 
[tab]They found another corpse yesterday...
[tab]It looked like it had been eaten...
[sync][wait][clear][end]

msg_21:
[color(yellow)]Tasaki[color(white)]
[tab]That’s scary.
[tab]They say that the Joker is a demon-user...
[tab]I hope nothing happens to you.
[sync][wait][clear][end]

msg_22:
[color(yellow)]Tasaki[color(white)]
[tab]Amano-san, you’re doing the Joker story, right? 
[tab]They found another corpse yesterday...
[tab]It looked like it had been eaten...
[sync][wait][clear][end]

msg_23:
[color(yellow)]Tasaki[color(white)]
[tab]That’s scary.
[tab]They say that the Joker is a demon-user...
[tab]I hope nothing happens to you.
[sync][wait][clear][end]

msg_24:
[color(yellow)]Veteran Reporter[color(white)]
[tab]The number of victims is in double digits.
[tab]What the hell are the police doing...
[sync][wait][clear][end]

msg_25:
[color(yellow)]Veteran Reporter[color(white)]
[tab]My friend at a journalist club says that
[tab]the police haven’t got a lead. I guess
[tab]that’s why there are so many rumors.
[sync][wait][clear][end]

msg_26:
[color(yellow)]Veteran Reporter[color(white)]
[tab]The number of victims is in double digits.
[tab]What the hell are the police doing...
[sync][wait][clear][end]

msg_27:
[color(yellow)]Veteran Reporter[color(white)]
[tab]My friend at a journalist club says that
[tab]the police haven’t got a lead. I guess
[tab]that’s why there are so many rumors.
[sync][wait][clear][end]

msg_28:
[color(yellow)]Senior Reporter[color(white)]
[tab]They found more rubble at that subway
[tab]construction site. Something’s under this
[tab]city. Man, I wanna go to my city official.
[sync][wait][clear][end]

msg_29:
[color(yellow)]Senior Reporter[color(white)]
[tab]They found more rubble at that subway
[tab]construction site. Something’s under this
[tab]city. Man, I wanna go to my city official.
[sync][wait][clear][end]

msg_30:
[color(yellow)]Yukino[color(white)]
[tab]Maya-san, Serizawa-san called.
[tab]She’s at the receptionist’s desk.
[sync][wait][clear][end]

msg_31:
[color(yellow)]Yukino[color(white)]
[tab]Maya-san, your friend hasn’t called yet.
[tab]What’s the big hurry?
[sync][wait][clear][end]

msg_32:
[color(yellow)]Emergency Staircase[color(green)]
[tab]You cannot enter here.[color(white)]
[sync][wait][clear][end]

msg_33:
[color(yellow)]Tasaki[color(white)]
[tab]Amano-san, you’re doing the Joker story, right? 
[tab]They found another corpse yesterday...
[tab]It looked like it had been eaten...
[sync][wait][clear][end]

msg_34:
[color(yellow)]Tasaki[color(white)]
[tab]That’s scary.
[tab]They say that the Joker is a demon-user...
[tab]I hope nothing happens to you.
[sync][wait][clear][end]

msg_35:
[color(yellow)]Veteran Reporter[color(white)]
[tab]The number of victims is in double digits.
[tab]What the hell are the police doing...
[sync][wait][clear][end]

msg_36:
[color(yellow)]Veteran Reporter[color(white)]
[tab]My friend at a journalist club says that
[tab]the police haven’t got a lead. I guess
[tab]that’s why there are so many rumors.
[sync][wait][clear][end]

msg_37:
[color(yellow)]Senior Reporter[color(white)]
[tab]More wreckage at that construction site.
[tab]There has to be something under this city.
[tab]Man, I want to go to the city department.
[sync][wait][clear][end]
