arcana_0:
?[end]

arcana_1:
Magician[end]

arcana_2:
Priestess[end]

arcana_3:
Empress[end]

arcana_4:
Emperor[end]

arcana_5:
Hierophant[end]

arcana_6:
Lovers[end]

arcana_7:
Chariot[end]

arcana_8:
Strength[end]

arcana_9:
Hermit[end]

arcana_10:
Fortune[end]

arcana_11:
Justice[end]

arcana_12:
Hanged Man[end]

arcana_13:
Death[end]

arcana_14:
Temperance[end]

arcana_15:
Devil[end]

arcana_16:
Tower[end]

arcana_17:
Star[end]

arcana_18:
Moon[end]

arcana_19:
Sun[end]

arcana_20:
Judgement[end]

arcana_21:
World[end]

arcana_22:
Fool[end]

arcana_23:
Wand[end]

arcana_24:
Cup[end]

arcana_25:
Sword[end]

arcana_26:
Coin[end]

arcana_27:
Human[end]

arcana_28:
Zombie[end]

arcana_29:
Rumor[end]

arcana_30:
Maskist[end]

arcana_31:
Aquarius[end]

arcana_32:
Zombie[end]

arcana_33:
Rumor[end]
