battle_0:
The enemy has ambushed you! [end]

battle_1:
Preemptive attack! [end]

battle_2:
 has been learned. [end]

battle_3:
Gained 2 ranks. [end]

battle_4:
Stats increased.[end]

battle_5:
Persona can change form.[end]

battle_6:
Proceed? [end]

battle_7:
Hidden ability activated! [end]

battle_8:
's party[end]

battle_9:
's party was defeated. [end]

battle_10:
Maya "Fire... I'm scared of fire!"[end]

battle_11:
Yes[end]

battle_12:
No[end]

battle_13:
Unknown ability awakened[end]

battle_14:
 escaped.[end]

battle_15:
 fell down.[end]

battle_16:
Counter[end]

battle_17:
 is exhausted.[end]

battle_18:
Select an action.[end]

battle_19:
Select a character to set actions.[end]

battle_20:
Select an action for [end]

battle_21:
Select a target.[end]

battle_22:
Select a skill to use.[end]

battle_23:
Select an item to use[end]

battle_24:
Select a Persona to change.[end]

battle_25:
Select a demon to analyze.[end]

battle_26:
Distribute 3 points.[end]

battle_27:
Select a character to change order.[end]

battle_28:
Select conditions for Fusion Spells.[end]

battle_29:
Select battle mode.[end]

battle_30:
Select tactical details.[end]

battle_31:
Select activation conditions.[end]

battle_32:
Automatically activate.[end]

battle_33:
Stand by.[end]

battle_34:
Will not activate even if the combination occurs[end]

battle_35:
Adjust various settings.[end]

battle_36:
Begin battle.[end]

battle_37:
Change battle behavior and view information[end]

battle_38:
Contact the enemy demons.[end]

battle_39:
View enemy demon data.[end]

battle_40:
Change battle settings.[end]

battle_41:
Escape from battle.[end]

battle_42:
Set individual actions.[end]

battle_43:
Change battle order.[end]

battle_44:
View fusion spells and set activation conditions[end]

battle_45:
Switch between normal and single[end]

battle_46:
Attack with the equipped weapon.[end]

battle_47:
Use Persona ability[end]

battle_48:
Use an item.[end]

battle_49:
Change Personas.[end]

battle_50:
View status for [end]

battle_51:
Concentrate on defending.[end]

battle_52:
End action settings.[end]

battle_53:
Have all allies Attack.[end]

battle_54:
Confirm this turn order.[end]

battle_55:
Reset turn order based on agility[end]

battle_56:
Continue fighting until canceled.[end]

battle_57:
Pause battle after next turn.[end]

battle_58:
Confirm settings and return.[end]

battle_59:
Status: Human + Persona[end]

battle_60:
Status: Human[end]

battle_61:
Status: Persona[end]

battle_62:
Affected by[end]

battle_63:
 is unconscious. [end]

battle_64:
Persona has been sealed.[end]

battle_65:
Persona has been sealed.[end]

battle_66:
Not enough SP.[end]

battle_67:
No items in inventory.[end]

battle_68:
An ally has taken this on.[end]

battle_69:
It is in no condition to answer.[end]

battle_70:
This ally cannot run.[end]

battle_71:
!!!!!!!!!!!![end]

battle_72:
Incompatible Persona[end]

battle_73:
Already taken on.[end]

battle_74:
This ally cannot act.[end]

battle_75:
Attack with equipped weapon[end]

battle_76:
Use Persona spells[end]

battle_77:
Use items[end]

battle_78:
Change persona[end]

battle_79:
Show status[end]

battle_80:
Defend against attacks[end]

battle_81:
Attack[end]

battle_82:
Spell[end]

battle_83:
Item[end]

battle_84:
Persona[end]

battle_85:
Status[end]

battle_86:
Defend[end]

battle_87:
Start the battle[end]

battle_88:
Change strategy[end]

battle_89:
Make contact with the enemy[end]

battle_90:
View enemy information[end]

battle_91:
Change settings[end]

battle_92:
Attempt to flee from battle[end]

battle_93:
Auto-battle in progress[end]

battle_94:
Unable to flee in hard mode[end]

battle_95:
Battle[end]

battle_96:
Strategy[end]

battle_97:
Contact[end]

battle_98:
Analyze[end]

battle_99:
Config[end]

battle_100:
Escape[end]

battle_101:
Set party behavior[end]

battle_102:
Adjust the turn order queue[end]

battle_103:
Set fusion spells[end]

battle_104:
Switch battle mode[end]

battle_105:
Save strategy[end]

battle_106:
Actions[end]

battle_107:
Order[end]

battle_108:
Fusion Spells[end]

battle_109:
Battle Mode[end]

battle_110:
Confirm[end]
