
location_0:
St. Hermelin Faculty Room[end]

location_1:
St. Hermelin School Gate[end]

location_2:
St. Hermelin Principal's Office[end]

location_3:
St. Hermelin Nurse's Office[end]

location_4:
St. Hermelin Courtyard[end]

location_5:
St. Hermelin 1-1[end]

location_6:
St. Hermelin 1-2[end]

location_7:
St. Hermelin 1-3[end]

location_8:
St. Hermelin 1-4[end]

location_9:
St. Hermelin 1-5[end]

location_10:
St. Hermelin 1-6[end]

location_11:
Velvet Room[end]

location_12:
St. Hermelin Passage[end]

location_13:
Reserved[end]

location_14:
Reserved[end]

location_15:
Reserved[end]

location_16:
St. Hermelin Cafeteria[end]

location_17:
St. Hermelin Home Economics Room[end]

location_18:
St. Hermelin 2-1[end]

location_19:
St. Hermelin 2-2[end]

location_20:
St. Hermelin 2-3[end]

location_21:
St. Hermelin 2-4[end]

location_22:
St. Hermelin 2-5[end]

location_23:
St. Hermelin 2-6[end]

location_24:
St. Hermelin Empty Classroom[end]

location_25:
Reserved[end]

location_26:
Reserved[end]

location_27:
Reserved[end]

location_28:
Reserved[end]

location_29:
Reserved[end]

location_30:
Reserved[end]

location_31:
Reserved[end]

location_32:
St. Hermelin Library[end]

location_33:
St. Hermelin Student Council Room[end]

location_34:
St. Hermelin Empty Room[end]

location_35:
St. Hermelin Art Room[end]

location_36:
St. Hermelin 3-1[end]

location_37:
St. Hermelin 3-2[end]

location_38:
St. Hermelin 3-3[end]

location_39:
St. Hermelin 3-4[end]

location_40:
St. Hermelin 3-5[end]

location_41:
St. Hermelin 3-6[end]

location_42:
St. Hermelin 3-7[end]

location_43:
Reserved[end]

location_44:
Reserved[end]

location_45:
Reserved[end]

location_46:
Reserved[end]

location_47:
Reserved[end]

location_48:
St. Hermelin Gym[end]

location_49:
St. Hermelin Storeroom[end]

location_50:
St. Hermelin Drama Club[end]

location_51:
St. Hermelin Boxing Club[end]

location_52:
St. Hermelin Archery Club[end]

location_53:
St. Hermelin Fencing Club[end]

location_54:
St. Hermelin Ballet Club[end]

location_55:
St. Hermelin Gymnastics Club[end]

location_56:
St. Hermelin Passage[end]

location_57:
Reserved[end]

location_58:
Reserved[end]

location_59:
Reserved[end]

location_60:
Reserved[end]

location_61:
Reserved[end]

location_62:
Reserved[end]

location_63:
Reserved[end]

location_64:
Trish's Fountain[end]

location_65:
Velvet Room[end]

location_66:
St. Hermelin School Gate[end]

location_67:
St. Hermelin 1-1[end]

location_68:
St. Hermelin 1-2[end]

location_69:
St. Hermelin 1-3[end]

location_70:
St. Hermelin 1-4[end]

location_71:
St. Hermelin 1-5[end]

location_72:
St. Hermelin 1-6[end]

location_73:
St. Hermelin 1-7[end]

location_74:
St. Hermelin 1-8[end]

location_75:
St. Hermelin Passage[end]

location_76:
Reserved[end]

location_77:
Reserved[end]

location_78:
Reserved[end]

location_79:
Reserved[end]

location_80:
St. Hermelin 2-1[end]

location_81:
St. Hermelin 2-2[end]

location_82:
St. Hermelin 2-3[end]

location_83:
St. Hermelin 2-4[end]

location_84:
St. Hermelin 2-5[end]

location_85:
St. Hermelin 2-6[end]

location_86:
St. Hermelin 2-7[end]

location_87:
St. Hermelin 2-8[end]

location_88:
St. Hermelin 2-9[end]

location_89:
St. Hermelin 2-10[end]

location_90:
St. Hermelin 2-11[end]

location_91:
St. Hermelin 2-12[end]

location_92:
St. Hermelin 2-13[end]

location_93:
St. Hermelin 2-14[end]

location_94:
St. Hermelin 2-15[end]

location_95:
St. Hermelin 2-16[end]

location_96:
Trish's Fountain[end]

location_97:
Velvet Room[end]

location_98:
St. Hermelin 3-1[end]

location_99:
St. Hermelin 3-2[end]

location_100:
St. Hermelin 3-3[end]

location_101:
St. Hermelin 3-4[end]

location_102:
St. Hermelin 3-5[end]

location_103:
St. Hermelin 3-6[end]

location_104:
St. Hermelin 3-7[end]

location_105:
St. Hermelin 3-8[end]

location_106:
St. Hermelin 3-9[end]

location_107:
St. Hermelin 3-10[end]

location_108:
St. Hermelin 3-11[end]

location_109:
St. Hermelin 3-12[end]

location_110:
St. Hermelin 3-13[end]

location_111:
St. Hermelin 3-14[end]

location_112:
St. Hermelin 3-15[end]

location_113:
St. Hermelin 3-16[end]

location_114:
St. Hermelin 3-17[end]

location_115:
St. Hermelin 3-18[end]

location_116:
St. Hermelin 3-19[end]

location_117:
Reserved[end]

location_118:
Reserved[end]

location_119:
Reserved[end]

location_120:
Reserved[end]

location_121:
Reserved[end]

location_122:
Reserved[end]

location_123:
Reserved[end]

location_124:
Reserved[end]

location_125:
Reserved[end]

location_126:
Reserved[end]

location_127:
Reserved[end]

location_128:
Trish's Fountain[end]

location_129:
St. Hermelin Drama Club[end]

location_130:
St. Hermelin Boxing Club[end]

location_131:
St. Hermelin Archery Club[end]

location_132:
St. Hermelin Fencing Club[end]

location_133:
St. Hermelin Ballet Club[end]

location_134:
St. Hermelin Gymnastics Club[end]

location_135:
St. Hermelin Empty Room 1[end]

location_136:
St. Hermelin Empty Room 2[end]

location_137:
St. Hermelin Empty Room 3[end]

location_138:
St. Hermelin Passage[end]

location_139:
Reserved[end]

location_140:
Reserved[end]

location_141:
Reserved[end]

location_142:
Reserved[end]

location_143:
Reserved[end]

location_144:
Karukozaka High Storeroom[end]

location_145:
Karukozaka High Boxing Club[end]

location_146:
Karukozaka High School Gate[end]

location_147:
Velvet Room[end]

location_148:
Karukozaka High Principal's Office[end]

location_149:
Trish's Fountain[end]

location_150:
Karukozaka High Computer Room[end]

location_151:
Karukozaka High Science Room[end]

location_152:
Karukozaka High Baseball Club[end]

location_153:
Karukozaka High Soccer Club[end]

location_154:
Karukozaka High Hockey Club[end]

location_155:
Karukozaka High Sumo Club[end]

location_156:
Karukozaka High In front of the Gym[end]

location_157:
Karukozaka High Gym[end]

location_158:
Reserved[end]

location_159:
Reserved[end]

location_160:
Karukozaka High Faculty Room[end]

location_161:
Karukozaka High Empty Classroom 1[end]

location_162:
Karukozaka High 2-A[end]

location_163:
Karukozaka High 2-B[end]

location_164:
Karukozaka High 2-C[end]

location_165:
Karukozaka High 2-D[end]

location_166:
Karukozaka High Empty Classroom 2[end]

location_167:
Karukozaka High Drama Club[end]

location_168:
Karukozaka High Art Room[end]

location_169:
Reserved[end]

location_170:
Reserved[end]

location_171:
Reserved[end]

location_172:
Reserved[end]

location_173:
Reserved[end]

location_174:
Reserved[end]

location_175:
Reserved[end]

location_176:
Karukozaka High Empty Room[end]

location_177:
Karukozaka High Student Council Room[end]

location_178:
Karukozaka High Storeroom[end]

location_179:
Karukozaka High Empty Classroom 1[end]

location_180:
Karukozaka High 2-E[end]

location_181:
Karukozaka High 2-F[end]

location_182:
Karukozaka High 2-G[end]

location_183:
Karukozaka High 2-H[end]

location_184:
Karukozaka High Library[end]

location_185:
Karukozaka High Empty Classroom 2[end]

location_186:
Reserved[end]

location_187:
Reserved[end]

location_188:
Reserved[end]

location_189:
Reserved[end]

location_190:
Reserved[end]

location_191:
Reserved[end]

location_192:
Karukozaka High Empty Classroom[end]

location_193:
Karukozaka High Empty Room[end]

location_194:
Karukozaka High Storeroom[end]

location_195:
Karukozaka High Classroom 1[end]

location_196:
Karukozaka High Classroom 2[end]

location_197:
Karukozaka High Classroom 3[end]

location_198:
Karukozaka High Classroom 4[end]

location_199:
Reserved[end]

location_200:
Reserved[end]

location_201:
Reserved[end]

location_202:
Reserved[end]

location_203:
Reserved[end]

location_204:
Reserved[end]

location_205:
Reserved[end]

location_206:
Reserved[end]

location_207:
Reserved[end]

location_208:
Karukozaka High Rooftop[end]

location_209:
Reserved[end]

location_210:
Reserved[end]

location_211:
Reserved[end]

location_212:
Reserved[end]

location_213:
Reserved[end]

location_214:
Reserved[end]

location_215:
Reserved[end]

location_216:
Reserved[end]

location_217:
Reserved[end]

location_218:
Reserved[end]

location_219:
Reserved[end]

location_220:
Reserved[end]

location_221:
Reserved[end]

location_222:
Reserved[end]

location_223:
Reserved[end]

location_224:
Karukozaka High Storeroom[end]

location_225:
Karukozaka High Boxing Club[end]

location_226:
Karukozaka High School Gate[end]

location_227:
Velvet Room[end]

location_228:
Karukozaka High Empty Classroom[end]

location_229:
Trish's Fountain[end]

location_230:
Karukozaka High Computer Room[end]

location_231:
Karukozaka High Science Room[end]

location_232:
Karukozaka High Baseball Club[end]

location_233:
Karukozaka High Soccer Club[end]

location_234:
Karukozaka High Hockey Club[end]

location_235:
Karukozaka High Sumo Club[end]

location_236:
Karukozaka High In front of the Gym[end]

location_237:
Karukozaka High Gym[end]

location_238:
Reserved[end]

location_239:
Reserved[end]

location_240:
Karukozaka High Faculty Room[end]

location_241:
Karukozaka High Empty Classroom 1[end]

location_242:
Karukozaka High 2-A[end]

location_243:
Karukozaka High 2-B[end]

location_244:
Karukozaka High 2-C[end]

location_245:
Karukozaka High 2-D[end]

location_246:
Karukozaka High Empty Classroom 2[end]

location_247:
Karukozaka High Drama Club[end]

location_248:
Karukozaka High Art Room[end]

location_249:
Reserved[end]

location_250:
Reserved[end]

location_251:
Reserved[end]

location_252:
Reserved[end]

location_253:
Reserved[end]

location_254:
Reserved[end]

location_255:
Reserved[end]

location_256:
Karukozaka High Hee-Ho Room[end]

location_257:
Karukozaka High Student Council Room[end]

location_258:
Karukozaka High Storeroom[end]

location_259:
Karukozaka High Classroom 1[end]

location_260:
Karukozaka High 2-E[end]

location_261:
Karukozaka High 2-F[end]

location_262:
Karukozaka High 2-G[end]

location_263:
Karukozaka High 2-H[end]

location_264:
Karukozaka High Library[end]

location_265:
Karukozaka High Classroom 2[end]

location_266:
Reserved[end]

location_267:
Reserved[end]

location_268:
Reserved[end]

location_269:
Reserved[end]

location_270:
Reserved[end]

location_271:
Reserved[end]

location_272:
Karukozaka High Empty Classroom[end]

location_273:
Karukozaka High Empty Room[end]

location_274:
Karukozaka High Storeroom[end]

location_275:
Karukozaka High Classroom 1[end]

location_276:
Karukozaka High Classroom 2[end]

location_277:
Karukozaka High Classroom[end]

location_278:
Karukozaka High Classroom[end]

location_279:
Reserved[end]

location_280:
Reserved[end]

location_281:
Reserved[end]

location_282:
Reserved[end]

location_283:
Reserved[end]

location_284:
Reserved[end]

location_285:
Reserved[end]

location_286:
Reserved[end]

location_287:
Reserved[end]

location_288:
Karukozaka High Rooftop[end]

location_304:
Trish's Fountain[end]

location_305:
Velvet Room[end]

location_306:
St. Hermelin School Gate[end]

location_307:
St. Hermelin 1-1[end]

location_308:
St. Hermelin 1-2[end]

location_309:
St. Hermelin 1-3[end]

location_310:
St. Hermelin 1-4[end]

location_311:
St. Hermelin 1-5[end]

location_312:
St. Hermelin 1-6[end]

location_313:
St. Hermelin 1-7[end]

location_314:
St. Hermelin 1-8[end]

location_315:
St. Hermelin Passage[end]

location_316:
Reserved[end]

location_317:
Reserved[end]

location_318:
Reserved[end]

location_319:
Reserved[end]

location_320:
St. Hermelin 2-1[end]

location_321:
St. Hermelin 2-2[end]

location_322:
St. Hermelin 2-3[end]

location_323:
St. Hermelin 2-4[end]

location_324:
St. Hermelin 2-5[end]

location_325:
St. Hermelin 2-6[end]

location_326:
St. Hermelin 2-7[end]

location_327:
St. Hermelin 2-8[end]

location_328:
St. Hermelin 2-9[end]

location_329:
St. Hermelin 2-10[end]

location_330:
St. Hermelin 2-11[end]

location_331:
St. Hermelin 2-12[end]

location_332:
St. Hermelin 2-13[end]

location_333:
St. Hermelin 2-14[end]

location_334:
St. Hermelin 2-15[end]

location_335:
St. Hermelin 2-16[end]

location_336:
Trish's Fountain[end]

location_337:
Velvet Room[end]

location_338:
St. Hermelin 3-1[end]

location_339:
St. Hermelin 3-2[end]

location_340:
St. Hermelin 3-3[end]

location_341:
St. Hermelin 3-4[end]

location_342:
St. Hermelin 3-5[end]

location_343:
St. Hermelin 3-6[end]

location_344:
St. Hermelin 3-7[end]

location_345:
St. Hermelin 3-8[end]

location_346:
St. Hermelin 3-9[end]

location_347:
St. Hermelin 3-10[end]

location_348:
St. Hermelin 3-11[end]

location_349:
St. Hermelin 3-12[end]

location_350:
St. Hermelin 3-13[end]

location_351:
St. Hermelin 3-14[end]

location_352:
St. Hermelin 3-15[end]

location_353:
St. Hermelin 3-16[end]

location_354:
St. Hermelin 3-17[end]

location_355:
St. Hermelin 3-18[end]

location_356:
St. Hermelin 3-19[end]

location_357:
Reserved[end]

location_358:
Reserved[end]

location_359:
Reserved[end]

location_360:
Reserved[end]

location_361:
Reserved[end]

location_362:
Reserved[end]

location_363:
Reserved[end]

location_364:
Reserved[end]

location_365:
Reserved[end]

location_366:
Reserved[end]

location_367:
Reserved[end]

location_368:
Trish's Fountain[end]

location_369:
St. Hermelin Drama Club[end]

location_370:
St. Hermelin Boxing Club[end]

location_371:
St. Hermelin Archery Club[end]

location_372:
St. Hermelin Fencing Club[end]

location_373:
St. Hermelin Ballet Club[end]

location_374:
St. Hermelin Gymnastics Club[end]

location_375:
St. Hermelin Empty Room 1[end]

location_376:
St. Hermelin Empty Room 2[end]

location_377:
St. Hermelin Empty Room 3[end]

location_378:
St. Hermelin Passage[end]

location_379:
Reserved[end]

location_380:
Reserved[end]

location_381:
Reserved[end]

location_382:
Reserved[end]

location_383:
Reserved[end]

location_384:
Karukozaka High Storeroom[end]

location_385:
Karukozaka High Boxing Club[end]

location_386:
Karukozaka High School Gate[end]

location_387:
Velvet Room[end]

location_388:
Karukozaka High Empty Classroom[end]

location_389:
Trish's Fountain[end]

location_390:
Karukozaka High Computer Room[end]

location_391:
Karukozaka High Science Room[end]

location_392:
Karukozaka High Baseball Club[end]

location_393:
Karukozaka High Soccer Club[end]

location_394:
Karukozaka High Hockey Club[end]

location_395:
Karukozaka High Sumo Club[end]

location_396:
Karukozaka High In front of the Gym[end]

location_397:
Karukozaka High Gym[end]

location_398:
Reserved[end]

location_399:
Reserved[end]

location_400:
Karukozaka High Faculty Room[end]

location_401:
Karukozaka High Empty Classroom 1[end]

location_402:
Karukozaka High 2-A[end]

location_403:
Karukozaka High 2-B[end]

location_404:
Karukozaka High 2-C[end]

location_405:
Karukozaka High 2-D[end]

location_406:
Karukozaka High Empty Classroom 2[end]

location_407:
Karukozaka High Drama Club[end]

location_408:
Karukozaka High Art Room[end]

location_409:
Reserved[end]

location_410:
Reserved[end]

location_411:
Reserved[end]

location_412:
Reserved[end]

location_413:
Reserved[end]

location_414:
Reserved[end]

location_415:
Reserved[end]

location_416:
Karukozaka High Hee-Ho Room[end]

location_417:
Karukozaka High Student Council Room[end]

location_418:
Karukozaka High Storeroom[end]

location_419:
Karukozaka High Classroom 1[end]

location_420:
Karukozaka High 2-E[end]

location_421:
Karukozaka High 2-F[end]

location_422:
Karukozaka High 2-G[end]

location_423:
Karukozaka High 2-H[end]

location_424:
Karukozaka High Library[end]

location_425:
Karukozaka High Classroom 2[end]

location_426:
Reserved[end]

location_427:
Reserved[end]

location_428:
Reserved[end]

location_429:
Reserved[end]

location_430:
Reserved[end]

location_431:
Reserved[end]

location_432:
Karukozaka High Empty Classroom[end]

location_433:
Karukozaka High Empty Room[end]

location_434:
Karukozaka High Storeroom[end]

location_435:
Karukozaka High Classroom 1[end]

location_436:
Karukozaka High Classroom 2[end]

location_437:
Karukozaka High Classroom[end]

location_438:
Karukozaka High Classroom[end]

location_439:
Reserved[end]

location_440:
Reserved[end]

location_441:
Reserved[end]

location_442:
Reserved[end]

location_443:
Reserved[end]

location_444:
Reserved[end]

location_445:
Reserved[end]

location_446:
Reserved[end]

location_447:
Reserved[end]

location_448:
Karukozaka High Rooftop[end]
