
map_help_0:
Exit[end]

map_help_1:
Upstairs[end]

map_help_2:
Recovery Room[end]

map_help_3:
HP Damage[end]

map_help_4:
Pitfall[end]

map_help_5:
Event[end]

map_help_6:
Door[end]

map_help_7:
Downstairs[end]

map_help_8:
Velvet Room[end]

map_help_9:
SP Damage[end]

map_help_10:
Conveyor[end]

map_help_11:
Message[end]

map_help_12:
Elevator[end]

map_help_13:
Items[end]

map_help_14:
Dark Zone[end]

map_help_15:
Poison Floor[end]

map_help_16:
Teleporter[end]
