
menu_0:
Skills[end]

menu_1:
Items[end]

menu_2:
Equip[end]

menu_3:
Persona[end]

menu_4:
Status[end]

menu_5:
Analyze[end]

menu_6:
Battle settings[end]

menu_7:
System[end]

menu_8:
View and use skills[end]

menu_9:
View and use items[end]

menu_10:
View and change equipment[end]

menu_11:
View and take on Personas[end]

menu_12:
View party information[end]

menu_13:
View demon and Persona information[end]

menu_14:
Change various battle settings[end]

menu_15:
View and change system settings[end]

menu_16:
Expendable items[end]

menu_17:
Key items[end]

menu_18:
Cards[end]

menu_19:
Use expendable items[end]

menu_20:
View plot-related items[end]

menu_21:
View cards on hand[end]

menu_22:
Tarot[end]

menu_23:
Material[end]

menu_24:
Skills[end]

menu_25:
Incense[end]

menu_26:
View Tarot Cards[end]

menu_27:
View Material Cards[end]

menu_28:
View Skill Cards[end]

menu_29:
View Incense Cards[end]

menu_30:
Demon[end]

menu_31:
Persona[end]

menu_32:
View demon information[end]

menu_33:
View Persona information[end]

menu_34:
Battle order settings[end]

menu_35:
Fusion Spells[end]

menu_36:
Set battle order[end]

menu_37:
View and set fusion spells[end]

menu_38:
Settings[end]

menu_39:
Quit[end]

menu_40:
Settings[end]

menu_41:
Save[end]

menu_42:
Load[end]

menu_43:
Title[end]

menu_44:
Quit[end]

menu_45:
Settings[end]

menu_46:
Save[end]

menu_47:
Load[end]

menu_48:
Title[end]

menu_49:
Change various game settings[end]

menu_50:
Quit quest[end]

menu_51:
Change various game settings[end]

menu_52:
Save game[end]

menu_53:
Load game[end]

menu_54:
Return to the title screen[end]

menu_55:
Change various game settings[end]

menu_56:
Save game[end]

menu_57:
Load game[end]

menu_58:
Return to the title screen[end]

menu_59:
Quit additional scenario[end]

menu_60:
Adjust message display speed[end]

menu_61:
Change music style[end]

menu_62:
Adjust BGM volume[end]

menu_63:
Adjust SE volume[end]

menu_64:
Adjust voice volume[end]

menu_65:
Remember last menu choice[end]

menu_66:
Toggle battle portrait cut-ins[end]

menu_67:
Change camera rotation direction[end]

menu_68:
Adjust movie display resolution[end]

menu_69:
Change combat difficulty[end]

menu_70:
Select region of Innocent Sin save file[end]

menu_71:
Change window color[end]
