party_0_name:
Atlus[end]

party_0_descr1:
[end]

party_0_descr2:
[end]

party_1_name:
Maya[end]

party_1_descr1:
Editor of Coolest. Cheerful
by nature, she has been
troubled by occurences
of déjà vu lately.[end]

party_1_descr2:
The woman of destiny who
holds 2 memories -- this
world's and the Other
Side's -- within herself.[end]

party_2_name:
Ulala[end]

party_2_descr1:
Maya's best friend who
likes fortune telling.
Tends to get excited
easily.[end]

party_2_descr2:
Woman who continues to
search for her goal in
life. Considerate of her
friends.[end]

party_3_name:
Katsuya[end]

party_3_descr1:
Sergeant of the Homicide
Division with a strong
sense of justice.[end]

party_3_descr2:
He gave up his dream to
find the one who framed
his father. Loves his
family above all.[end]

party_4_name:
Baofu[end]

party_4_descr1:
Insolent Tap Buster who
gathers information for
some unknown reason.[end]

party_4_descr2:
Kaoru Saga, former Sumaru
City public prosecutor. He
was thought to have been
killed by Tatsuzou's scheme.[end]

party_5_name:
Nanjo[end]

party_5_descr1:
Soon-to-be leader of Nanjo
Conglomerate. He became
a Persona user during the
Sebec Scandal.[end]

party_5_descr2:
Soon-to-be leader of Nanjo
Conglomerate. He became
a Persona user during the
Sebec Scandal.[end]

party_6_name:
Elly[end]

party_6_descr1:
Fashion model who studies
at a college. She became
a Persona user during the
Sebec Scandal.[end]

party_6_descr2:
Fashion model who studies
at a college. She became
a Persona user during the
Sebec Scandal.[end]

party_7_name:
[tatsuya][end]

party_7_descr1:
Katsuya's brother whom
Maya refers to as the
Déjà Vu Boy. He seems
to be after the Joker.[end]

party_7_descr2:
Young man whose heart is
filled with deep sorrow.
[tatsuya]'s mind from the
Other Side is in his body.[end]
